[package]
name = "wire"
version = "0.1.0"
std = "c99"
compiler = "clang"

[[target]]
name = "wire"
type = "executable"
src = ["src/**/*.c"]
include = ["include"]
out = "build"
links = []

[profile.debug]
flags = ["-g", "-fsanitize=address,undefined", "-O0"]

[profile.release]
flags = ["-O3", "-DNDEBUG"]

[install]
prefix = "/usr/local"
