[package]
name = "wire"
version = "0.1.0"
compiler = "clang"

[[target]]
name = "wire"
src = ["src/srv/**/*.c"]
include = ["include/srv"]

[[target]]
name = "wirec"
src = ["src/cli/**/*.c"]
include = ["include/cli"]
